# Generated by Django 4.1.3 on 2023-03-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_feedbackdata_formdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackdata',
            name='user_name',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
