# Generated by Django 4.1.3 on 2023-03-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_feedbackdata_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdata',
            name='user_name',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
